package com.mcnc.yuga.helper.key;

public enum ProfitCenterFlag {
	
	REVENUE_SERVICE,
	REVENUE_LICENSE,
	REVENUE_3RD_PARTY,
	REVENUE_INTERNAL_RD,
	
	COST_TEAM_INTERNAL,
	COST_INTERNAL_OUTSOURCING,
	COST_OUTSOURCING,
	COST_SALES_OPEX,
	COST_PROJECT_EXPENSE,
	
	GP_SERVICE,
	GP_LICENSE,
	GP_3RD_PARTY
}
